import '@/styles/globals.css'
import Footer from '@/ui/components/Footer'
import Header from '@/ui/components/Header'
import type { AppProps } from 'next/app'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
    <Head>
        <title>Proedev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head> 
    <main>
      <Header/>
        <Component {...pageProps} />
      <Footer/>
    </main>
  
  </>
  )
  
  
}
